const Constants = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REDUCE_FROM_CART: "REDUCE_FROM_CART",
    FETCH_CART_DETAILS: 'FETCH_CART_DETAILS',
    CREATE_ORDER : "CREATE_ORDER",
    CLEAR_ORDER : "CLEAR_ORDER",
    CLEAR_CART : "CLEAR_CART",
    FETCH_ORDERS : "FETCH_ORDERS"

}
export default Constants;
